stages:
  - test
  - build

pylint:
  image: python:3
  stage: test
  allow_failure: true
  script:
    - pip install pylint
    - pip install -r ${CI_PROJECT_DIR}/requirements.txt
    - pylint ${CI_PROJECT_DIR}/brewwolf/brewwolf/*.py ${CI_PROJECT_DIR}/brewwolf/rate_beer/*.py

dependenciesCheck:
  image: python:3
  stage: test
  script:
    - pip install safety
    - safety check -r ${CI_PROJECT_DIR}/requirements.txt

securityCheck:
  image: python:3
  stage: test
  script:
    - pip install bandit
    - bandit ${CI_PROJECT_DIR}/brewwolf/brewwolf/*.py ${CI_PROJECT_DIR}/brewwolf/rate_beer/*.py

kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "${GOOGLE_APPLICATION_CREDENTIALS_JSON}" > $GOOGLE_APPLICATION_CREDENTIALS
    - /kaniko/executor --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_REGISTRY_IMAGE:latest --context dir://$CI_PROJECT_DIR/
